repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v18.1.8'
    hooks:
      - id: clang-format
        types: ["c++"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        types_or: ["javascript", "css"]
        args: ["--line-width", "88", "--indent-style", "space"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.(cpp|h)$
        args:
          - --license-filepath
          - .github/license_header.txt
          - --comment-style
          - //
          - --use-current-year
