#cmakedefine PROJECT_VERSION "@CMAKE_PROJECT_VERSION@"
#cmakedefine WITH_LAYER_SHELL
#cmakedefine ENABLE_X11
#cmakedefine ENABLE_WAYLAND
#cmakedefine WITH_TRANSLATIONS
#cmakedefine LINUX_DIST_FLATPAK
