#cmakedefine PROJECT_VERSION "@CMAKE_PROJECT_VERSION@"
#cmakedefine WITH_TRANSLATIONS
#cmakedefine LINUX_DIST_FLATPAK
#cmakedefine BUNDLE_QT_TRANSLATIONS
#cmakedefine CMAKE_INSTALL_LIBDIR "@CMAKE_INSTALL_LIBDIR@"
