#ifndef SANE_PREFERENCES_DEFAULT_H
#define SANE_PREFERENCES_DEFAULT_H

#define SANE_BREAK_SMALL_EVERY 1200
#define SANE_BREAK_SMALL_FOR 20
#define SANE_BREAK_BIG_AFTER 3
#define SANE_BREAK_BIG_FOR 60

#endif  // SANE_PREFERENCES_DEFAULT_H
