# Modified from (GPL):
# https://github.com/travisgoodspeed/maskromtool/blob/master/.github/workflows/build.yml

name: Build app

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.ts'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  test:
    name: Test (Trixie)
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      !startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    # We need newer version of Qt to run the tests
    container:
      image: debian:trixie
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y g++ cmake qt6-base-dev qt6-multimedia-dev libgmock-dev libxss-dev

    - name: Run Tests
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        mkdir build
        cd build
        cmake -DTESTING=ON  ..
        cmake --build . --parallel --target check

  build-windows:
    name: Build (Windows)
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: AllanChain/install-qt-static@v6.9
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build Project
      run: |
        mkdir build
        cd build
        qt-cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
        cmake --build . --parallel --config Release

    - name: Packing
      run: |
        mkdir release
        mv build\Release\sane-break.exe .
        7z a release/sane-break-windows.zip sane-break.exe LICENSE

    - name: Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ./release/*

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
         name: "sane-break-windows"
         path: ./release/*

  build-macos:
    name: Build (macOS, ${{ matrix.arch }})
    needs: test
    runs-on: macos-15
    strategy:
      fail-fast: false # continue other jobs if one failed
      matrix:
        arch: [x86_64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: AllanChain/install-qt-static@v6.9

    - name: Build Project
      run: |
        mkdir build
        cd build
        qt-cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} ..
        cmake --build . --parallel

    - uses: apple-actions/import-codesign-certs@v3
      id: certificate
      with:
        p12-file-base64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}

    # https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/
    - name: Codesign app
      env:
        MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
      run: codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime "build/sane-break.app" -v

    - name: Notarize app
      env:
        PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
        PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
        PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
      run: |
        echo "Create keychain profile"
        xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"

        echo "Creating temp notarization archive"
        ditto -c -k --keepParent "build/sane-break.app" "notarization.zip"

        echo "Notarize app"
        xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait

        echo "Attach staple"
        xcrun stapler staple "build/sane-break.app"

    - name: Packing
      run: |
        mv build/sane-break.app "build/Sane Break.app"
        mkdir release
        brew install create-dmg
        create-dmg \
          --volname "Sane Break" \
          --hide-extension "Sane Break.app" \
          --window-size 600 450 \
          --icon-size 94 \
          --icon "Sane Break" 141 249 \
          --app-drop-link 458 249 \
          --eula LICENSE \
          "release/sane-break-macos-${{ matrix.arch }}.dmg" \
          "build/Sane Break.app"

    - name: Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ./release/*

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
         name: "sane-break-macos-${{ matrix.arch }}"
         path: ./release/*

  build-x11:
    name: Build (X11)
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake qt6-base-dev qt6-multimedia-dev qt6-tools-dev libxss-dev

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DSANE_MAKE_DEB=1 ..
        cmake --build . --parallel

    - name: Packing
      run: |
        mkdir release
        cd build
        cpack
        mv sane-break.deb ../release/sane-break-x11.deb

    - name: Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ./release/*

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
         name: "sane-break-x11"
         path: ./release/*

  build-wayland:
    name: Build (Wayland, ${{ matrix.distro }})
    needs: test
    strategy:
      fail-fast: false # continue other jobs if one failed
      matrix:
        distro: [ubuntu, debian]
        include:
          - distro: debian
            tag: trixie
          - distro: ubuntu
            tag: oracular
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.distro }}:${{ matrix.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y nodejs g++ cmake qt6-base-dev qt6-multimedia-dev qt6-tools-dev qt6-wayland-dev

    - name: Install additional dependencies
      if: matrix.tag == 'trixie'
      run: apt-get install -y liblayershellqtinterface-dev

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DSANE_MAKE_DEB=1 ..
        cmake --build . --parallel

    - name: Packing
      run: |
        mkdir release
        cd build
        cpack
        mv sane-break.deb ../release/sane-break-wayland-${{ matrix.distro }}-${{ matrix.tag }}.deb

    - name: Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ./release/*

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
         name: "sane-break-wayland-${{ matrix.distro }}-${{ matrix.tag }}"
         path: ./release/*

  build-gnome:
    name: Build GNOME shell extension
    needs: test
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      !startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Packing
      run: zip -j -r sane-break-gnome-extension packaging/linux/gnome/sane-break@allanchain.github.io

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
         name: "sane-break-gnome-extension"
         path: ./sane-break-gnome-extension.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows, build-wayland, build-x11, build-gnome]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body: |
            ## What's new

            ## Installation instructions

            ### macOS

            Download `sane-break-macos-x86_64.dmg` file if you are using Intel mac, or `sane-break-macos-arm64` if you are using ARM chip. Open and install it. macOS 13 or newer are supported.

            ### Windows

            Download the `sane-break-windows.zip` extract it. Put the `.exe` executable anywhere you like. x86 version of Windows 10 or newer is supported. Older versions may be supported too.

            ### Linux

            If you are using X11, `sane-break-x11.deb` is for you.

            If you are using Ubuntu 24.10 (and above) or Debian Trixie (and above), you can install the `.deb` package. For GNOME users, make sure to enable the GNOME shell extension with:
            ```bash
            gnome-extensions enable sane-break@allanchain.github.io
            ```
            The difference between Wayland Ubuntu Oracular build and Debian Trixie build is the layer shell support. If you are using a Debian-based distro and a Wayland compositor with layer shell protocol support (e.g. KDE Neon), you probably need the Debian Trixie build. Otherwise, the Ubuntu Oracular build is good to go.
