# Modified from (GPL):
# https://github.com/travisgoodspeed/maskromtool/blob/master/.github/workflows/build.yml

name: Build app

on:
  push:
    branches-ignore:
      - 'pre-commit-ci-update-config'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.ts'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build-debian:
    name: Build (Linux, ${{ matrix.tag }})
    strategy:
      fail-fast: false # continue other jobs if one failed
      matrix:
        tag: [bookworm, trixie]
    runs-on: ubuntu-latest
    container:
      image: debian:${{ matrix.tag }}
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LANGUAGE: C.UTF-8
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y nodejs g++ cmake libxss-dev \
          qt6-base-dev qt6-multimedia-dev qt6-tools-dev \
          qt6-wayland-dev qt6-wayland qt6-base-private-dev

    - name: Install additional dependencies
      if: matrix.tag == 'trixie'
      run: apt-get install -y liblayershellqtinterface-dev

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=/usr -DSANE_MAKE_DEB=1 ..
        cmake --build . --parallel
        ls
        cat config.h

    - name: Packing
      run: |
        mkdir release
        cd build
        cpack
        mv sane-break.deb ../release/sane-break-${{ matrix.tag }}.deb

    - name: Attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: ./release/*

    - name: Create Artifact
      uses: actions/upload-artifact@v5
      with:
         name: "sane-break-${{ matrix.tag }}"
         path: ./release/*
