name: Build on macOS

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Clone Project
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j3
        macdeployqt sane-break.app -dmg

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
         name: "Sane Break (macOS)"
         path: ./build/sane-break.dmg
